[server]
maxUploadSize = 200

[theme]
base = "dark"
primaryColor       = "#6366f1"
backgroundColor    = "#09090b"
secondaryBackgroundColor = "#18181b"
textColor          = "#fafafa"
font               = "sans serif"

[browser]
gatherUsageStats = false
